server:
  port: 30300

spring:
  application:
    name: alinesno-infra-data-scheduler-boot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_data_scheduler_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adminer
    # druid-specific 配置
    druid:
      # 连接池大小
      initial-size: 10       # 初始连接数
      min-idle: 10           # 最小空闲连接数
      max-active: 150         # 最大连接数（根据并发和 DB 能力调整）
      max-wait: 60000        # 获取连接最大等待毫秒数
      # 校验/回收
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # 监控与防火墙
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 其他可选项
      keep-alive: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: aip@local
    mongodb:
      uri: mongodb://localhost:27017/infra_scheduler_logs
      database: infra_scheduler_logs
